name: Afisha Check

on:
  schedule:
    # UTC+3 time: 11:00
    # Converting to UTC: 08:00
    - cron: '0 8 * * *'  # 11:00 UTC+3
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  check-afisha:
    uses: ./.github/workflows/global-checks.yml
    with:
      python-version: '3.11'
      cache-key: 'shows'
      cache-path: 'shows.json'
      script-name: 'afisha.py'
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_IDS: ${{ secrets.CHAT_IDS }} 