name: Global Checks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      cache-key:
        required: true
        type: string
      cache-path:
        required: true
        type: string
      script-name:
        required: true
        type: string
    secrets:
      BOT_TOKEN:
        required: true
      CHAT_IDS:
        required: true

jobs:
  setup-and-run:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libatspi2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libxshmfence1 \
          xdg-utils
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright
      run: |
        playwright install chromium
        playwright install-deps

    - name: Fetch state branch and shows.json
      run: |
        git fetch origin state:state || git checkout --orphan state
        git checkout state
        cp shows.json $GITHUB_WORKSPACE/shows.json || echo "No previous shows.json"
        git checkout $GITHUB_REF_NAME

    - name: Run Script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_IDS: ${{ secrets.CHAT_IDS }}
      run: python ${{ inputs.script-name }}

    - name: Commit and push updated shows.json to state branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        rm -f shows.json
        git checkout state
        # No need to copy, file is already present
        git add shows.json
        git commit -m "Update shows state [skip ci]" || echo "No changes to commit"
        git push origin state
        rm -f shows.json
        git checkout $GITHUB_REF_NAME 