# .github/workflows/scraper.yml

name: Ticket Seat Scraper 🤖

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scrape_seats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run the scraper script
        run: python scrap.py

      # 👇 ADD THIS STEP TO SAVE THE SCREENSHOT
      - name: Upload screenshot artifact on failure
        # This step will only run if the previous step (running the script) fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png # The name of the file your script creates