# .github/workflows/scraper.yml

name: Ticket Seat Scraper 🤖

on:
  workflow_dispatch:
    inputs:
      test_urls:
        description: 'Comma-separated TCE ticket URLs (optional)'
        required: false
        default: ''
      seats_out_file:
        description: 'Output JSON filename (optional)'
        required: false
        default: 'selenium_seats.json'
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scrape_seats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests

      - name: Run Selenium seats scraper
        env:
          TCE_TEST_URLS: ${{ github.event.inputs.test_urls }}
          SELENIUM_SEATS_FILE: ${{ github.event.inputs.seats_out_file }}
        run: |
          python selenium_seats.py

      - name: Upload seats JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-seats
          path: ${{ github.event.inputs.seats_out_file }}

      - name: Upload screenshot artifact on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png