name: Ticket Check

on:
  schedule:
    # UTC+3 time: 9:00-18:00
    # Converting to UTC: 6:00-15:00
    - cron: '0 6 * * *'  # 9:00 UTC+3
    - cron: '0 7 * * *'  # 10:00 UTC+3
    - cron: '0 8 * * *'  # 11:00 UTC+3
    - cron: '0 9 * * *'  # 12:00 UTC+3
    - cron: '0 10 * * *' # 13:00 UTC+3
    - cron: '0 11 * * *' # 14:00 UTC+3
    - cron: '0 12 * * *' # 15:00 UTC+3
    - cron: '0 13 * * *' # 16:00 UTC+3
    - cron: '0 14 * * *' # 17:00 UTC+3
    - cron: '0 15 * * *' # 18:00 UTC+3
  workflow_dispatch: # Allow manual triggering

jobs:
  check-tickets:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libatspi2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libxshmfence1 \
          xdg-utils
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright
      run: |
        playwright install chromium
        playwright install-deps

    - name: Cache tickets data
      uses: actions/cache@v4
      with:
        path: seats.json
        key: tickets-${{ runner.os }}
        restore-keys: |
          tickets-${{ runner.os }}-

    - name: Run Tickets-Check
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_IDS: ${{ secrets.CHAT_IDS }}
      run: python tickets.py 