name: Ticket Check 

on:
  schedule:
    - cron: '0 10,15 * * 3,5'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-tickets:
    uses: ./.github/workflows/global-checks.yml
    with:
      python-version: '3.11'
      cache-key: 'tickets'
      cache-path: 'seats.json'
      script-name: 'tickets.py'
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_IDS: ${{ secrets.CHAT_IDS }}